/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package form;

import DAO.ChiTietTaiKhoanDAO;
import DAO.ChiTietXeDAO;
import DAO.DanhGiaDAO;
import Hepler.DialogHelper;
import entyti.ChiTietTaiKhoan;
import entyti.ChiTietXe;
import entyti.DanhGia;
import entyti.TaiKhoan;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class DanhGiaDialog extends java.awt.Dialog {

    DanhGiaDAO dgd = new DanhGiaDAO();
    ChiTietTaiKhoanDAO cttkd = new ChiTietTaiKhoanDAO();
    ChiTietXeDAO ctxd = new ChiTietXeDAO();
    List<DanhGia> all_danhgia = new ArrayList<>();

    /**
     * Creates new form DanhGiaDialog
     */
    public DanhGiaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        filltable_danhgia(getListDanhGia());
        setLocationRelativeTo(null);
        setTitle("Đánh Giá");
        fillcbb_sanpham();
        TaiKhoan tk = Hepler.AuthHelper.user;
        String userid = String.valueOf(tk.getUserid());
        ChiTietTaiKhoan cttk = cttkd.selectByID_DOITUONG(userid);
        txt_hoten.setText(cttk.getHoten());
    }

    public DanhGia getForm() {
        int sosao_danhgia = cbb_saodanhgia.getSelectedIndex() + 1;
        String tenxe = cbb_sanPham.getSelectedItem().toString();
        ChiTietXe ctx = ctxd.selectByID_TENXE(tenxe);
        TaiKhoan tk = Hepler.AuthHelper.user;
        DanhGia dg = new DanhGia();
        dg.setUserid(tk.getUserid());
        dg.setMaxe(ctx.getMaxe());
        dg.setNoidung(txt_noidung.getText());
        dg.setNgaydanhgia(Hepler.DateHelper.now());
        dg.setSosaodanhgia(sosao_danhgia);
        return dg;
    }

    public void themDanhGia() {
        DanhGia dg = getForm();
        try {
            dgd.insert(dg);
            DialogHelper.alert(this, "Thêm Đánh Giá Thành Công");
            filltable_danhgia(getListDanhGia());
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm Đánh Giá Thất Bại");
            System.out.println(e.getMessage());
        }
    }

    public List<DanhGia> getListDanhGia() {
        try {
            all_danhgia = dgd.selectAll();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return all_danhgia;
    }

    public void timkiem() {
        try {
            TaiKhoan tk = Hepler.AuthHelper.user;
            List<DanhGia> list_find_danhgia = dgd.selectByID_userid(String.valueOf(tk.getUserid()));
            filltable_danhgia(list_find_danhgia);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void fillcbb_sanpham() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cbb_sanPham.getModel();
            model.removeAllElements();
            List<ChiTietXe> list = ctxd.selectAll();
            for (ChiTietXe ctx : list) {
                model.addElement(ctx.getTenxe());
            }
            cbb_sanPham.setSelectedIndex(0);
        } catch (Exception e) {
            Hepler.DialogHelper.alert(this, "Hiện Tại Bạn Chưa Có Đánh Giá Nào");
            System.out.println(e.getMessage());
        }
    }

    public void filltable_danhgia(List<DanhGia> list) {
        DefaultTableModel model = (DefaultTableModel) tbl_danhgia.getModel();
        model.setRowCount(0);
        try {
            for (DanhGia dg : list) {
                ChiTietTaiKhoan cttk = cttkd.selectByID_DOITUONG(String.valueOf(dg.getUserid()));
                ChiTietXe ctx = ctxd.selectByID_MAXE(dg.getMaxe());
                Object[] row = {
                    cttk.getHoten(),
                    ctx.getTenxe(),
                    dg.getNoidung(),
                    dg.getNgaydanhgia(),
                    dg.getSosaodanhgia()
                };
                model.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhgia = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_noidung = new javax.swing.JTextArea();
        cbb_saodanhgia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbb_sanPham = new javax.swing.JComboBox<>();
        btn_timkiem = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        tbl_danhgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ Tên", "Sản Phẩm", "Nội Dung", "Ngày Đánh Giá", "SỐ Sao Đánh Giá"
            }
        ));
        tbl_danhgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhgiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhgia);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");

        btn_xoa.setText("Xoá");

        jLabel1.setText("Họ Tên");

        txt_hoten.setEnabled(false);

        jLabel2.setText("Nội Dung");

        txt_noidung.setColumns(20);
        txt_noidung.setRows(5);
        jScrollPane2.setViewportView(txt_noidung);

        cbb_saodanhgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel3.setText("Số Sao");

        jLabel4.setText("Sản Phẩm");

        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_sua)
                        .addGap(18, 18, 18)
                        .addComponent(btn_xoa))
                    .addComponent(jLabel4)
                    .addComponent(cbb_sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_saodanhgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txt_hoten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timkiem))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_saodanhgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        themDanhGia();
    }//GEN-LAST:event_btn_themActionPerformed

    private void tbl_danhgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhgiaMouseClicked
        // TODO add your handling code here:
        int row = -1;
        row = tbl_danhgia.getSelectedRow();
        String hoten = (String) tbl_danhgia.getValueAt(row, 0);
        try {
            ChiTietTaiKhoan cttk = cttkd.selectByID_DOITUONG_HOTEN(hoten);
            DanhGia dg = dgd.selectByID_userid_doituong(String.valueOf(cttk.getUserid()));
            txt_noidung.setText(dg.getNoidung());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tbl_danhgiaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbb_sanPham;
    private javax.swing.JComboBox<String> cbb_saodanhgia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_danhgia;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextArea txt_noidung;
    // End of variables declaration//GEN-END:variables
}
