/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import DAO.TaiKhoanDAO;
import Hepler.DialogHelper;
import entyti.TaiKhoan;

/**
 *
 * @author Hieu
 */
public class DoiMatKhauDialog extends javax.swing.JDialog {
    TaiKhoanDAO tkd = new TaiKhoanDAO();
    /**
     * Creates new form DoiMatKhauDialog
     */
    public DoiMatKhauDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Đổi Mật Khẩu");
        setIconImage(Hepler.ImagesHelper.getAppIcon());
        setLocationRelativeTo(null);
    }
    public boolean veirfy(){
        if(txt_matkhaucu.getPassword().equals("")){
            DialogHelper.alert(this, "Thông Tin Không Được Để Trống");
            txt_matkhaucu.requestFocus();
            return false;
        }
        if(txt_matkhaumoi.getPassword().equals("")){
            DialogHelper.alert(this, "Thông Tin Không Được Để Trống");
            txt_matkhaumoi.requestFocus();
            return false;
        }
        if(txt_matkhauxacnhan.getPassword().equals("")){
            DialogHelper.alert(this, "Thông Tin Không Được Để Trống");
            txt_matkhauxacnhan.requestFocus();
            return false;
        }
        if (!String.valueOf(txt_matkhauxacnhan.getPassword()).equals(String.valueOf(txt_matkhaumoi.getPassword()))) {
            DialogHelper.alert(this, "Mật Khẩu Xác Nhận Phải Nhập Trùng");
            txt_matkhauxacnhan.requestFocus();
            return false;
        }
        if (String.valueOf(txt_matkhaumoi.getPassword()).length() < 6) {
            DialogHelper.alert(this, "Mật Khẩu Kí tự Lớn hơn 6");
            txt_matkhaumoi.requestFocus();
            return false;
        }
        TaiKhoan tk = Hepler.AuthHelper.user;
        if(!tk.getMatkhau().equalsIgnoreCase(String.valueOf(txt_matkhaucu.getPassword()))){
            DialogHelper.alert(this, "Mật Khẩu Bạn Nhập Không Đúng");
            txt_matkhaucu.requestFocus();
        }
        return true;
    }
    void update() {
        TaiKhoan tk = Hepler.AuthHelper.user;
        tk.setMatkhau(String.valueOf(txt_matkhaumoi.getPassword()));
            try {
                tkd.update(tk);
                DialogHelper.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
                DialogHelper.alert(this, "Cập nhật thất bại");
                e.printStackTrace();
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_matkhaucu = new javax.swing.JLabel();
        txt_matkhaucu = new javax.swing.JPasswordField();
        lbl_matkhaumoi = new javax.swing.JLabel();
        txt_matkhaumoi = new javax.swing.JPasswordField();
        lbl_matkhauxacnhan = new javax.swing.JLabel();
        txt_matkhauxacnhan = new javax.swing.JPasswordField();
        btn_xacnhan = new javax.swing.JButton();
        cb_hienthimatkhau = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_matkhaucu.setText("Mật Khẩu Cũ");
        lbl_matkhaucu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_matkhaucuMouseClicked(evt);
            }
        });

        txt_matkhaucu.setText("jPasswordField1");

        lbl_matkhaumoi.setText("Mật Khẩu Mới");
        lbl_matkhaumoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_matkhaumoiMouseClicked(evt);
            }
        });

        txt_matkhaumoi.setText("jPasswordField1");

        lbl_matkhauxacnhan.setText("Xác Nhận Mật Khẩu");
        lbl_matkhauxacnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_matkhauxacnhanMouseClicked(evt);
            }
        });

        txt_matkhauxacnhan.setText("jPasswordField1");

        btn_xacnhan.setText("Xác Nhận");
        btn_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhanActionPerformed(evt);
            }
        });

        cb_hienthimatkhau.setText("HIỂN THỊ MẬT KHẨU");
        cb_hienthimatkhau.setContentAreaFilled(false);
        cb_hienthimatkhau.setFocusPainted(false);
        cb_hienthimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hienthimatkhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_hienthimatkhau)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_xacnhan)
                        .addComponent(lbl_matkhauxacnhan)
                        .addComponent(lbl_matkhaumoi)
                        .addComponent(lbl_matkhaucu)
                        .addComponent(txt_matkhaucu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txt_matkhaumoi)
                        .addComponent(txt_matkhauxacnhan)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_matkhaucu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_matkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_matkhaumoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_matkhauxacnhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_matkhauxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_hienthimatkhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_xacnhan)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_hienthimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hienthimatkhauActionPerformed
        // TODO add your handling code here:
        if (cb_hienthimatkhau.isSelected()) {
            txt_matkhaucu.setEchoChar((char) 0); // password visible
            txt_matkhaumoi.setEchoChar((char) 0); // password visible
            txt_matkhauxacnhan.setEchoChar((char) 0); // password visible
        } else {
            txt_matkhaucu.setEchoChar('*'); // password hidden
            txt_matkhaumoi.setEchoChar('*'); // password hidden
            txt_matkhauxacnhan.setEchoChar('*'); // password hidden
        }
    }//GEN-LAST:event_cb_hienthimatkhauActionPerformed

    private void btn_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhanActionPerformed
        // TODO add your handling code here:
        if(veirfy()){
            update();
        }
    }//GEN-LAST:event_btn_xacnhanActionPerformed

    private void lbl_matkhaucuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_matkhaucuMouseClicked
        // TODO add your handling code here:
        txt_matkhaucu.setText("");
    }//GEN-LAST:event_lbl_matkhaucuMouseClicked

    private void lbl_matkhaumoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_matkhaumoiMouseClicked
        // TODO add your handling code here:
        txt_matkhaumoi.setText("");
    }//GEN-LAST:event_lbl_matkhaumoiMouseClicked

    private void lbl_matkhauxacnhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_matkhauxacnhanMouseClicked
        // TODO add your handling code here:
        txt_matkhauxacnhan.setText("");
    }//GEN-LAST:event_lbl_matkhauxacnhanMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_xacnhan;
    private javax.swing.JCheckBox cb_hienthimatkhau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_matkhaucu;
    private javax.swing.JLabel lbl_matkhaumoi;
    private javax.swing.JLabel lbl_matkhauxacnhan;
    private javax.swing.JPasswordField txt_matkhaucu;
    private javax.swing.JPasswordField txt_matkhaumoi;
    private javax.swing.JPasswordField txt_matkhauxacnhan;
    // End of variables declaration//GEN-END:variables
}
